import type { Metadata } from "next";
import { Header } from "@/components/shared";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Pizza | We are sall best quality pizza",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal:React.ReactNode;
}>) {
  return (
    <Suspense>
      <main className="min-h-screen">
        <Header/>
        {children}
        {modal}
      </main>
    </Suspense>
   
  );
}
